exclude: ^(data|sprout)/

substitutions:
  - &exclude
    exclude: ^(cfme|scripts) # for now disable - we shall gradually reenable it
repos:
- repo: https://github.com/asottile/seed-isort-config
  rev: v1.2.0
  hooks:
  - id: seed-isort-config
    args: [--exclude, "^data/.*|^sprout/"]
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
  - id: isort
    exclude: ^(cfme|scripts)
- repo: https://github.com/ambv/black
  rev: 18.6b4
  hooks:
  - id: black
    args: [--safe, --line-length, '100']
    language_version: python3.6
    <<: *exclude
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
    exclude: ^(sprout|scripts|cfme/fixtures/rdb.py)
  - id: flake8
- repo: https://github.com/asottile/pyupgrade
  rev: v1.6.0
  hooks:
  - id: pyupgrade
