exclude: ^(data|sprout)/

substitutions:
  - &exclude
    exclude: ^(cfme|scripts) # for now disable - we shall gradually reenable it
repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.6.1
  hooks:
  - id: reorder-python-imports
- repo: https://github.com/ambv/black
  rev: 19.3b0
  hooks:
  - id: black
    args: [--safe, --line-length, '100']
    language_version: python3.7
    <<: *exclude
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
    exclude: ^(sprout|scripts|cfme/fixtures/rdb.py)
  - id: flake8
    language_version: python3.7
    additional_dependencies: [polarion-docstrings, bugzilla-docstrings]
- repo: https://github.com/asottile/pyupgrade
  rev: v1.23.0
  hooks:
  - id: pyupgrade
    language_version: python3.7
    <<: *exclude
