# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0023_provider_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='suggested_delete',
            field=models.BooleanField(
                default=False, help_text=b'Whether Sprout suggests deleting this template.'),
        ),
    ]
