# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0025_auto_20160106_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='parent_template',
            field=models.ForeignKey(
                blank=True,
                help_text=b'What was source of this template?',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='child_templates',
                to='appliances.Template'),
        ),
    ]
