# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('appliances', '0028_auto_20160311_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='user_groups',
            field=models.ManyToManyField(
                blank=True, to='auth.Group',
                help_text=b'We can specify the providers that are tied to a specific user group.'),
        ),
    ]
