# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0029_provider_user_groups'),
        ('appliances', '0029_provider_hidden'),
    ]

    operations = [
    ]
