# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('appliances', '0030_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupShepherd',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_meta_data', models.TextField(default=b'{}\n')),
                ('template_pool_size', models.IntegerField(
                    default=0, help_text=b'How many appliances to keep spinned for quick taking.')),
                ('unconfigured_template_pool_size', models.IntegerField(
                    default=0,
                    help_text=(
                        b'How many appliances to keep spinned for quick taking - unconfigured ones.'
                    ))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='group',
            name='template_pool_size',
        ),
        migrations.RemoveField(
            model_name='group',
            name='unconfigured_template_pool_size',
        ),
        migrations.AddField(
            model_name='groupshepherd',
            name='template_group',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='appliances.Group'),
        ),
        migrations.AddField(
            model_name='groupshepherd',
            name='user_group',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
