# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0031_auto_20160511_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='HWProfile',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('remote_uuid', models.CharField(
                    blank=True,
                    help_text=(
                        b'If a HW profile is remote, it is not possible to edit it. Like a RHOS '
                        'Flavour.'),
                    max_length=36, null=True)),
                ('cpu', models.IntegerField(blank=True, help_text=b'CPU count', null=True)),
                ('ram', models.IntegerField(blank=True, help_text=b'RAM amount', null=True)),
                ('group', models.ManyToManyField(
                    related_name='hardware_profiles', to='appliances.Group')),
                ('provider', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='hardware_profiles',
                    to='appliances.Provider')),
            ],
        ),
    ]
