# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0030_bugquery'),
        ('appliances', '0031_auto_20160506_0848'),
    ]

    operations = [
    ]
