# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0031_auto_20160511_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='suggested_templates_delete',
            field=models.BooleanField(
                default=False, help_text=b'Enable deleting of suggested templates'),
        ),
        migrations.AddField(
            model_name='template',
            name='keep',
            field=models.BooleanField(
                default=False,
                help_text=b'Whether Sprout should refrain from deleting this template'),
        ),
    ]
