# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0031_auto_20160511_0826'),
        ('appliances', '0032_merge'),
    ]

    operations = [
    ]
