# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0033_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='allow_renaming',
            field=models.BooleanField(
                default=False, help_text=b'Whether this provider can rename appliances.'),
        ),
    ]
