# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-07 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0035_auto_20160922_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='ga_released',
            field=models.BooleanField(default=False),
        ),
    ]
