# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-30 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0032_hwprofile'),
        ('appliances', '0036_template_ga_released'),
    ]

    operations = [
    ]
