# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-31 16:12


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0037_auto_20170131_1058'),
    ]

    operations = [
    ]
