# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-03 09:18


from django.db import migrations, models
import django.utils.timezone


def appliances_forwards(apps, schema_editor):
    Appliance = apps.get_model("appliances", "Appliance")  # noqa
    for appliance in Appliance.objects.using(schema_editor.connection.alias).all():
        changed = False
        current_latest = None
        if appliance.datetime_leased:
            appliance.created_on = appliance.datetime_leased
            current_latest = appliance.created_on
            changed = True
        if (
                (not current_latest and appliance.status_changed) or
                (current_latest < appliance.status_changed)):
            current_latest = appliance.status_changed
        if (
                (not current_latest and appliance.power_state_changed) or
                (current_latest < appliance.power_state_changed)):
            current_latest = appliance.power_state_changed
        if current_latest:
            changed = True
        if changed:
            appliance.save()


def appliance_pools_forwards(apps, schema_editor):
    AppliancePool = apps.get_model("appliances", "AppliancePool")  # noqa
    Appliance = apps.get_model("appliances", "Appliance")  # noqa
    for pool in AppliancePool.objects.using(schema_editor.connection.alias).all():
        created_on_dates = sorted(
            [appliance.created_on for appliance in Appliance.objects.filter(appliance_pool=pool)],
            reverse=True)
        if created_on_dates:
            pool.created_on = created_on_dates[0]
        else:
            pool.created_on = django.utils.timezone.now()
        pool.modified_on = pool.created_on
        pool.save()


def templates_forwards(apps, schema_editor):
    Template = apps.get_model("appliances", "Template")  # noqa
    for template in Template.objects.using(schema_editor.connection.alias).all():
        template.created_on = template.date
        template.save()


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0038_auto_20170201_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='appliance',
            name='modified_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(appliances_forwards, do_nothing),
        migrations.AddField(
            model_name='appliancepool',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='appliancepool',
            name='modified_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(appliance_pools_forwards, do_nothing),
        migrations.AddField(
            model_name='delayedprovisiontask',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='delayedprovisiontask',
            name='modified_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='group',
            name='modified_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='groupshepherd',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='groupshepherd',
            name='modified_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='provider',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='modified_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='template',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='template',
            name='modified_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(templates_forwards, do_nothing),
    ]
