# Generated by Django 1.9.12 on 2017-01-31 16:12


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0041_auto_20170131_1518'),
    ]

    operations = [
    ]
