# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-05 21:54


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0045_appliancepool_template_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliancepool',
            name='is_container',
        ),
    ]
