# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-01 13:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0045_auto_20170403_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appliance',
            options={
                'ordering': ['name', 'id'],
                'permissions': (('can_modify_hw', 'Can modify HW configuration'),)},
        ),
        migrations.AlterModelOptions(
            name='appliancepool',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='groupshepherd',
            options={'ordering': ['template_group', 'user_group', 'id']},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['name', 'original_name', 'provider', 'id']},
        ),
        migrations.AddField(
            model_name='appliancepool',
            name='provider_type',
            field=models.CharField(default=b'', max_length=32),
        ),
    ]
