# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-06 17:34


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0046_remove_appliancepool_is_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='ip_address',
            field=models.CharField(help_text=b"Appliance's IP address", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='openshift_ext_ip',
            field=models.CharField(help_text=b"Openshift's project external ip", max_length=64,
                                   null=True),
        ),
    ]
