# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-16 16:34


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0046_auto_20180201_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliancepool',
            name='provider_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
