# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-07 10:19


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0047_ipaddress_made_bigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='openshift_project',
            field=models.CharField(help_text=b"Openshift's project name", max_length=64, null=True),
        ),
    ]
