# Generated by Django 1.9.13 on 2018-02-19 12:23


from django.db import migrations, models
from django.contrib.postgres.fields import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0047_auto_20180216_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='openshift_ext_ip',
            field=models.CharField(help_text=b"Openshift's project external ip", max_length=45,
                                   null=True),
        ),
        migrations.AddField(
            model_name='appliance',
            name='openshift_project',
            field=models.CharField(help_text=b"Openshift's project name", max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='custom_data',
            field=JSONField(default={}, help_text=b'Some Templates '
                                                  b'require additional data '
                                                  b'for deployment'),
        ),
    ]
