# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-23 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0048_openshift_project_made_bigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugquery',
            name='owner',
        ),
        migrations.DeleteModel(
            name='BugQuery',
        ),
    ]
