# -*- coding: utf-8 -*-
from pomoc.navigator import Navigator
from pomoc.objects import View

from .widgets import TopMenuItem, SecondMenuItem


class IntelligenceMenu(View):
    dashboard = SecondMenuItem('Dashboard')
    reports = SecondMenuItem('Reports')
    chargeback = SecondMenuItem('Chargeback')
    timelines = SecondMenuItem('Timelines')
    rss = SecondMenuItem('RSS')


class TopMenu(View):
    intelligence = TopMenuItem('Cloud Intel')
    insights = TopMenuItem('Red Hat Insights')
    services = TopMenuItem('Services')
    compute = TopMenuItem('Compute')
    configuration = TopMenuItem('Configuration')
    networks = TopMenuItem('Networks')
    control = TopMenuItem('Control')
    automate = TopMenuItem('Automate')
    optimize = TopMenuItem('Optimize')
    settings = TopMenuItem('Settings')

    def on_view(self):
        return self.intelligence.is_displayed

    # These can be autogenerated in future
    @Navigator.transition_to(IntelligenceMenu)
    def go_to_cloud_intel(self):
        self.intelligence.click()
