#!/bin/bash

touch .yaml_key
mkdir -p /cfme-qe-yamls/complete
cp conf/* /cfme-qe-yamls/complete

vncserver :99 -xstartup /xstartup -SecurityTypes None

source /cfme_venv/bin/activate
# python -m cfme.scripting.quickstart
py.test cfme/tests/test_login.py -k test_login -v
