#!/bin/bash

touch .yaml_key
mkdir -p /cfme-qe-yamls/complete
cp conf/* /cfme-qe-yamls/complete

vncserver :99 -xstartup /xstartup -SecurityTypes None -geometry 1280x1024

source /cfme_venv/bin/activate
pip install -e .
miq-runtest $@
