pytest_plugins = """
    markers.composite
    markers.crud
    markers.fixtureconf
    markers.meta
    markers.stream_excluder
    markers.requires
    markers.sauce
    markers.skipper
    markers.uses
    markers.uncollect
    markers.smoke
    markers.composite
    markers.crud
    markers.fixtureconf
    markers.meta
    markers.stream_excluder
    markers.requires
    markers.sauce
    markers.skipper
    markers.uses
    markers.uncollect
    markers.smoke
    markers.polarion
""".strip().split()
