FROM fedora:25
RUN dnf install -y \
		gcc-c++ postgresql-devel libxml2-devel libxslt-devel zeromq3-devel git nano python-devel gnupg gnupg2 \
		libcurl-devel redhat-rpm-config findutils libffi-devel openssl-devel python-virtualenv && dnf clean all

RUN git config --global user.email "me@dockerbot" && \
    git config --global user.name "DockerBot" &&  \
    git config --global gpg.program gpg2

