#!/usr/bin/env python3
from __future__ import absolute_import, unicode_literals

import re
import sys

import os
os.environ["RUNNING_UNDER_SPROUT"] = "true"  # To prevent importing unnecessary UI stuff

from celery.__main__ import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    try:
        sys.exit(main())
    finally:
        del os.environ["RUNNING_UNDER_SPROUT"]
